### ISSUE TITLE
enum MsoFeatureInstall doesn't declare

### ISSUE THREAD

**Issue by xhmbs** [katecpp/MailReader#1]
I have used dumpcpp to create MSOULT.h and MSOUTL.cpp
but running goes wrong with MSOULT.h

error: use of enum 'MsoFeatureInstall' without previous declaration

how to solve please

**Comment by katecpp** [comment]
Please use the solution described in last post (from 26th January 2011, 11:43) on this page:
http://www.qtcentre.org/archive/index.php/t-8811.html

**Comment by xhmbs** [comment]
Thanks,solved.
And do you have a MailSend like this ,  I really need it
